version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: workforall-db-dev
    environment:
      POSTGRES_USER: workforall
      POSTGRES_PASSWORD: workforall
      POSTGRES_DB: workforall
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data_dev:
